export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS:       'INVALID_CREDENTIALS',
  TOKEN_EXPIRED:             'TOKEN_EXPIRED',
  TOKEN_INVALID:             'TOKEN_INVALID',
  REFRESH_TOKEN_REVOKED:     'REFRESH_TOKEN_REVOKED',
  ACCOUNT_LOCKED:            'ACCOUNT_LOCKED',

  // Products
  PRODUCT_NOT_FOUND:         'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_EXISTS:        'PRODUCT_SKU_EXISTS',
  PRODUCT_INACTIVE:          'PRODUCT_INACTIVE',
  INSUFFICIENT_STOCK:        'INSUFFICIENT_STOCK',

  // Orders
  ORDER_NOT_FOUND:           'ORDER_NOT_FOUND',
  ORDER_ALREADY_PAID:        'ORDER_ALREADY_PAID',
  ORDER_ALREADY_CANCELLED:   'ORDER_ALREADY_CANCELLED',
  INVALID_ORDER_TRANSITION:  'INVALID_ORDER_TRANSITION',
  EMPTY_ORDER:               'EMPTY_ORDER',
  CONCURRENT_MODIFICATION:   'CONCURRENT_MODIFICATION',
  MISSING_IDEMPOTENCY_KEY:   'MISSING_IDEMPOTENCY_KEY',
  DUPLICATE_IDEMPOTENCY_KEY: 'DUPLICATE_IDEMPOTENCY_KEY',

  // Lookups
  INVALID_LOOKUP_CODE:       'INVALID_LOOKUP_CODE',
  LOOKUP_TYPE_NOT_FOUND:     'LOOKUP_TYPE_NOT_FOUND',
  LOOKUP_VALUE_NOT_FOUND:    'LOOKUP_VALUE_NOT_FOUND',
  LOOKUP_CODE_EXISTS:        'LOOKUP_CODE_EXISTS',
  LOOKUP_VALUE_PROTECTED:    'LOOKUP_VALUE_PROTECTED',
  ENTITY_TYPE_NOT_FOUND:     'ENTITY_TYPE_NOT_FOUND',

  // General
  NOT_FOUND:                 'NOT_FOUND',
  VALIDATION_FAILED:         'VALIDATION_FAILED',
  DUPLICATE_ENTRY:           'DUPLICATE_ENTRY',
  FOREIGN_KEY_VIOLATION:     'FOREIGN_KEY_VIOLATION',
  FORBIDDEN:                 'FORBIDDEN',
  UNAUTHORIZED:              'UNAUTHORIZED',
  RATE_LIMIT_EXCEEDED:       'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR:            'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
