ALTER TABLE `customers` ADD `website` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `logo_uri` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `pan_number` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `override_credit_limit` integer;--> statement-breakpoint
ALTER TABLE `customers` ADD `payment_term_lookup_fk` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `payment_term_days` integer;--> statement-breakpoint
ALTER TABLE `customers` ADD `address_line_1` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `address_line_2` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `city` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `district` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `state_lookup_fk` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `pin_code` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `birthday` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `anniversary` text;--> statement-breakpoint
ALTER TABLE `customers` ADD `notes` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `display_name` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `website` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `logo_uri` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `pan_number` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `payment_term_lookup_fk` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `payment_term_days` integer;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `credit_limit` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `override_credit_limit` integer;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `address_line_1` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `address_line_2` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `city` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `district` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `state_lookup_fk` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `pin_code` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `notes` text;